name: Bug Report
description: Report a problem to Botanical Machinery Extra
title: "[BUG]"
labels: [ bug ]
body:
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft version
      options:
        - 1.18.2
        - 1.19.2
        - 1.20.1
  - type: dropdown
    id: problem-machinery-mod-version
    attributes:
      label: This problem exists in the Botanical Machinery mod.
      options:
        - "Yes"
        - "No"
  - type: input
    id: mod-version
    attributes:
      label: Version
      placeholder: eg. 1.19.2-1.0.0
    validations:
      required: true
  - type: input
    id: botanicalmachinery-version
    attributes:
      label: Botanical Machinery Version
      placeholder: eg. 1.19.2-2.0.5
    validations:
      required: true
  - type: input
    id: libx-version
    attributes:
      label: LibX version
      placeholder: eg. 1.19.2-4.2.8
    validations:
      required: true
  - type: input
    id: botania-version
    attributes:
      label: Botania version
      placeholder: eg. 1.19.2-440.2-FORGE
    validations:
      required: true
  - type: input
    id: appliedenergistics2-version
    attributes:
      label: Applied Energistics 2 version
      placeholder: eg. 1.19.2-12.9.9
    validations:
      required: true
  - type: input
    id: forge-version
    attributes:
      label: Forge version
      placeholder: eg. 43.4.0
    validations:
      required: true
  - type: input
    id: log-file
    attributes:
      label: The latest.log file
      description: |
        Please use a paste site such as [pastebin](https://pastebin.com/) / etc.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      placeholder: A description of the issue.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    id: additional-information
    attributes:
      label: Other information
      description: Any other relevant information that is related to this issue, such as modpacks, other mods and their versions.
